os: linux
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    # Minimal version (skip clippy)
    - rust: 1.33.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo build --verbose --all-targets
        - cargo test --verbose
        - cargo fmt -- --check
 
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo build --verbose --all-targets
  - cargo clippy --verbose --all-targets -- -D warnings
  - cargo test --verbose
  - cargo fmt -- --check
