[package]
name = "rob"
version = "0.2.0-pre"
authors = ["Eduardo Sánchez Muñoz <esm@eduardosm.net>"]
description = "Reference-or-box, with similar functionality to Cow"
repository = "https://github.com/eduardosm/rust-rob"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
